name: build-pcoip-bx

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * MON'  # 02h00 UTC (two hours after) https://github.com/toolbx-images/images
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  image: pcoip-bx
  registry: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pcoip-version:
          - 23.12.2
          - 23.08.1
          - 23.06.2
        ubuntu-version:
          - 22.04
          - 20.04
        include:
          - pcoip-version: 23.06.2
            ubuntu-version: 22.04
            is_latest: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        run: podman login --username ${{ github.actor }} --password ${{ github.token }} ${{ env.registry }}

      - name: Build image
        run: |

          podman --log-level=error build --format=docker --file Containerfile \
            --build-arg=PCOIP_VERSION=${{ matrix.pcoip-version }} \
            --build-arg=UBUNTU_VERSION=${{ matrix.ubuntu-version }} \
            --tag ${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }}

      - name: Push image
        run: |
          podman push --quiet --disable-content-trust --tls-verify=true \
            ${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }} \
            ${{ env.registry }}/${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }}

          if [[ "${{ matrix.is_latest }}" == "true" ]]; then
            podman push --quiet --disable-content-trust --tls-verify=true \
              ${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }} \
              ${{ env.registry }}/${{ env.image }}:latest
          fi

      - name: Log out of registry
        run: |
          podman logout ${{ env.registry }}
