name: build-pcoip-bx

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * MON'  # 02h00 UTC (two hours after) https://github.com/toolbx-images/images
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  image: pcoip-bx
  registry: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pcoip-version: [ "23.06.2", "23.08.1" ]
        ubuntu-version: [ "20.04", "22.04" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        run: podman login --username ${{ github.actor }} --password ${{ github.token }} ${{ env.registry }}

      - name: Build image
        run: |
          podman --log-level=error build --format=docker --file Containerfile \
            --build-arg=PCOIP_VERSION=${{ matrix.pcoip-version }} \
            --build-arg=UBUNTU_VERSION=${{ matrix.ubuntu-version }} \
            --tag ${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }}

      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ${{ env.registry }}
          image: ${{ env.image }}
          tags:
            ${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }}
          extra-args: |
            --disable-content-trust

      - name: Push image
        run: |
          podman push --quiet ${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }} ${{ env.registry }}/${{ env.image }}:${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }} --disable-content-trust --tls-verify=true

      - name: Log out of registry
        run: |
          podman logout ${{ env.registry }}
