name: build-pcoip-bx

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * MON'  # 02h00 UTC (two hours after) https://github.com/toolbx-images/images
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  image: pcoip-bx
  registry: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pcoip-version: [ "23.06.2", "23.08.1" ]
        ubuntu-version: [ "20.04", "22.04" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        id: image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles:
            Containerfile
          image: ${{ env.image }}
          tags: ${{ matrix.pcoip-version }}-${{ matrix.ubuntu-version }}
          build-args: |
            PCOIP_VERSION=${{ matrix.pcoip-version }}
            UBUNTU_VERSION=${{ matrix.ubuntu-version}}
          oci: false
          extra-args: |
            --log-level error

      - name: Push To Registry
        id: registry-push
        uses: redhat-actions/push-to-registry@v2
        env:
          REGISTRY_URL: ghcr.io/${{ github.repository_owner }}
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.image-build.outputs.image }}
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
